# Project information
site_name: Rock Major Element Analysis Protocol
site_description: Protocol describing the steps involved in analysing the major element composition of a rock sample
site_author: Jóhann Gunnarsson Robin
#site_url: https://squidfunk.github.io/mkdocs-material/
nav:
    - Home: index.md

# Repository
#repo_name: squidfunk/mkdocs-material
#repo_url: https://github.com/squidfunk/mkdocs-material

# Copyright
#copyright: Copyright &copy; 2020 Martin Donath

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: white
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/squidfunk

# Google Analytics
#google_analytics:
#  - UA-XXXXXXXX-X
#  - auto

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true